# Generated by Django 5.2 on 2026-02-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event_note_url'),
        ('blog', 'migration_bbnote'),
    ]

    operations = [
    ]
