# Generated by Django 5.2 on 2026-08-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_merge_0002_event_note_url_migration_bbnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, help_text='Sign-up link (e.g. Google Form) shown as a Register button', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6c5ce7', max_length=7),
        ),
        migrations.AlterField(
            model_name='event',
            name='note_url',
            field=models.URLField(blank=True, help_text='Link to note.com article', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
