# Generated by Django 5.2 on 2026-08-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_event_registration_url_alter_category_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
