# Generated by Django 5.2 on 2026-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'About Us (home page)'), ('community', 'Community'), ('members', 'Members'), ('project_bunni', 'Project Bunni')], max_length=30, unique=True)),
                ('heading', models.CharField(blank=True, help_text='Big title at the top of the page', max_length=200)),
                ('intro', models.CharField(blank=True, help_text='One line under the title (optional)', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Main text. Blank lines start a new paragraph.')),
                ('image', models.ImageField(blank=True, help_text='Optional image shown with the text', null=True, upload_to='pages/')),
                ('cta_label', models.CharField(blank=True, help_text="Button text, e.g. 'Join our Discord'", max_length=60)),
                ('cta_url', models.URLField(blank=True, help_text='Where the button links to')),
                ('meta_description', models.CharField(blank=True, help_text='Search-engine and social-preview description (optional)', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page text',
                'verbose_name_plural': 'Page texts',
                'ordering': ['page'],
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-is_featured', 'order', 'name']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show on the website'),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='', help_text='Name shown on the site', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, help_text='A short line or two about them'),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Without the @', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show first'),
        ),
        migrations.AlterField(
            model_name='member',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio or website'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('organizer', 'Organizer'), ('artist', 'Artist'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
