# Generated by Django 5.2 on 2026-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_gallery_rework_and_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to hide this event without deleting it.', verbose_name='Show on the website'),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers come first. Leave at 0 to sort by date.', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text="Filled in automatically from the name. This is the part that appears in the page's link.", max_length=80, unique=True, verbose_name='Web address'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="The large image at the top of the event's page.", verbose_name='Use as the main photo'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers come first.', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="This piece becomes the picture on the artist's folder in the Gallery.", verbose_name='Use as the folder cover'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Untick to hide this piece without deleting it.', verbose_name='Show on the website'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Lower numbers come first within this artist's folder.", verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.CharField(blank=True, help_text='Optional keywords, separated by commas. Not shown on the website — they are for your own searching.', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured members appear before everyone else.', verbose_name='Pin to the top'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Untick to hide this person without deleting them.', verbose_name='Show on the website'),
        ),
        migrations.AlterField(
            model_name='member',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers come first, among members who are not pinned.', verbose_name='Position'),
        ),
    ]
