# Generated by Django 5.2 on 2026-08-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_hide_undated_wachaj2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbnote',
            name='description',
            field=models.CharField(blank=True, help_text='Short description (optional)', max_length=300, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='bbnote',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned notes appear first.', verbose_name='Pin to the top'),
        ),
        migrations.AlterField(
            model_name='bbnote',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Untick to hide without deleting.', verbose_name='Show on the website'),
        ),
        migrations.AlterField(
            model_name='bbnote',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers come first.', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='bbnote',
            name='published_date',
            field=models.DateField(blank=True, help_text='When the article was published on note.com', null=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='bbnote',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Preview image (optional)', null=True, upload_to='bbnotes/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='bbnote',
            name='url',
            field=models.URLField(help_text='Full URL from note.com', max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Received'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Tick once you have dealt with it.', verbose_name='Read'),
        ),
    ]
