# Generated by Django 5.2 on 2026-08-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_plain_language_labels_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='blog.member', verbose_name='Artist (member profile)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='artist_name',
            field=models.CharField(blank=True, help_text='Credit for an artist who is not on the Members page. Ignored when an artist is chosen above.', max_length=120, verbose_name='Artist name (guest)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: the event this was shown at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='blog.event', verbose_name='Shown at event'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Artwork'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title of the piece'),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, help_text='A short line or two about them', verbose_name='Short bio'),
        ),
        migrations.AlterField(
            model_name='member',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discord username'),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Without the @', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='member',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio or website', verbose_name='Portfolio link'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('organizer', 'Organizer'), ('artist', 'Artist'), ('member', 'Member')], default='member', max_length=20, verbose_name='Role'),
        ),
    ]
