"""
Django settings for brushbunni project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Read secrets/flags from the environment, with safe defaults so a plain
# deploy keeps working until these env vars are set on the server.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-iwifad*kl2dp&8at6=j9qr2!&e=)jbi#c&t(l*gvq-x82ev(@l',
)

# Defaults to True; set DJANGO_DEBUG=False in production to turn it off.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() != 'false'

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'brushbunni.com,www.brushbunni.com,localhost,127.0.0.1',
).split(',')

# Required for admin/form POSTs over HTTPS once DEBUG is off (Django 4+).
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://brushbunni.com,https://www.brushbunni.com',
).split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # powers /sitemap.xml
    'blog',  # Your existing blog app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serve static with compression + caching
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'brushbunni.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'brushbunni.wsgi.application'

# The admin is the only login on this site. Without this, logging in straight
# from /admin/login/ lands on Django's default /accounts/profile/, which 404s.
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The community and its events are based in Japan — keep "today" (used to split
# upcoming vs past events) on local time, not UTC, which is 9 hours behind.
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
# No STATICFILES_DIRS needed: blog/static/ is found by the app-directories
# finder. Listing it again made collectstatic report every file as a duplicate.

# Enhanced: Media files configuration for image uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Enhanced: Static files for production (when you deploy)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: compress collected static files.
#
# In production the Manifest variant renames every file to include a content
# hash (style.4f2a9c.css). That is what makes a one-year Cache-Control safe:
# a changed file gets a new name, so browsers fetch it instead of serving a
# stale copy. Under DEBUG the manifest does not exist yet, and {% static %}
# would raise "Missing staticfiles manifest entry", so keep the plain backend.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage" if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        )
    },
}

# Serve collected static straight from WhiteNoise with a long cache lifetime.
# Only safe together with the hashed names above.
WHITENOISE_MAX_AGE = 31536000  # 1 year

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Enhanced: Email configuration for contact forms
# For development, use console backend (emails will show in terminal)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Enhanced: File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Enhanced: Custom settings for your site
SITE_SETTINGS = {
    'POSTS_PER_PAGE': 6,
    'GALLERY_ITEMS_PER_PAGE': 24,
    'PRODUCTS_PER_PAGE': 12,
    'MEMBERS_PER_PAGE': 12,
    'EVENTS_PER_PAGE': 6,
}

JAZZMIN_SETTINGS = {
    "site_title": "BrushBunni Admin",
    "site_header": "🎨 BrushBunni",
    "site_brand": "BrushBunni",
    "welcome_sign": "Welcome to BrushBunni Admin",
    "copyright": "BrushBunni Art Community",
    "search_model": ["blog.Event"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "blog.Event": "fas fa-calendar-alt",
        "blog.EventPhoto": "fas fa-images",
        "blog.Member": "fas fa-users",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-danger",
    "accent": "accent-danger",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-danger",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
# Production hardening — applied only when DEBUG is off. The HTTPS-dependent
# parts stay behind DJANGO_HTTPS so turning them on can't lock you out before
# TLS + a proxy that sets X-Forwarded-Proto are confirmed on the server.
if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'

    if os.environ.get('DJANGO_HTTPS', 'False').lower() == 'true':
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_SSL_REDIRECT = True
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '31536000'))
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True